import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import {
  PremuiButton,
  PremuiCard,
  PremuiCollapsible,
  PremuiExpandButton,
  PremuiLoading,
  PremuiSpacer,
  PremuiToggleButton,
  PremuiIcon,
  PremuiTabItem,
  PremuiTabs,
  PremuiExpandToggle,
  PremuiTitleBar,
  PremuiSideMenu,
  PremuiInput,
  PremuiTextArea,
  PremuiSwitchElement,
  PremuiSwitch,
} from './components';

@NgModule({
  declarations: [
    PremuiIcon,
    PremuiButton,
    PremuiCard,
    PremuiLoading,
    PremuiSpacer,
    PremuiToggleButton,
    PremuiCollapsible,
    PremuiTabs,
    PremuiTabItem,
    PremuiExpandButton,
    PremuiExpandToggle,
    PremuiTitleBar,
    PremuiSideMenu,
    PremuiInput,
    PremuiTextArea,
    PremuiSwitch,
    PremuiSwitchElement,
  ],
  imports: [CommonModule],
  exports: [
    PremuiIcon,
    PremuiButton,
    PremuiCard,
    PremuiLoading,
    PremuiSpacer,
    PremuiToggleButton,
    PremuiCollapsible,
    PremuiTabs,
    PremuiTabItem,
    PremuiExpandButton,
    PremuiExpandToggle,
    PremuiTitleBar,
    PremuiSideMenu,
    PremuiInput,
    PremuiTextArea,
    PremuiSwitch,
    PremuiSwitchElement,
  ],
})
export class PremuiAngularComponentsModule {}
